---
title: Project Proposal
author:
- Collin Farrell
- Paarth Mahajan
- Aayush Sharma
- Tony Zheng
format:
    html:
        embed-resources: true
---

## Project Title
Effect of Weather, Day of Season, and Registration Status on Bike Rentals 

## Research Questions

### (RQ.1)
Does the temperature of a day affect the number of Bike Rentals after accounting for other weather conditions (e.g. precipitation, humidity, and wind speed), user type and type of day (workday/not)?

### (RQ.2)
Does the fact that it is a workday (not a weekend/holiday) affect the number of Bike Rentals after accounting for weather conditions (e.g. precipitation, humidity, temperature, and wind speed), and user type?

### (RQ.3)
Do weather conditions affect the number of Bike Rentals among registered users vs. casual users?

### (RQ.4)
Does the fact that it is a workday (or not) affect the number of Bike Rentals among registered users vs. casual users differently?

### (RQ.5)
Do the number of rentals change through a season (e.g. do rentals taper of as a season progresses)?

## Model

The response variable of our model will be the number of rentals each hour (both for casual users, and registered users). Denoting the number of bike rentals at hour $i$ to be $Y_i$ (one of `casual` or `registered` in the dataset), we assume
$$
Y_i \sim \text{Poisson}(\lambda_i) \\
$$

with link function
$$
\log(\lambda_i) = X^T\beta
$$

for $X \in \mathbb{R}^{(p+1) \times n}$ and $\beta \in \mathbb{R}^{p + 1}$, where $n$ is the number of samples in the hour dataset times two (with samples of registered and casual rentals at each hour), and $p$ is the number of predictors we're including, or the number of rows in the [Predictors](#predictors) section. Then, we would have an intercept term $\beta_0$ with $X_{i, 1} = 1$.

## Predictors

Our model will include:

| Predictor | Reason |
| ----- | ----------- |
| `temp`, `windspeed`, `humidity` | To control for the effect of the different aspects of the weather on the number of bike rentals |
| `weathersit` | To examine the effect of the amount of precipitation on the number of bike rentals, after accounting for other parts of the weather |
| User Type | The user type for the count (whether the count was of registered or casual users). This will be taken from the `casual` and `registered` columns of the dataset. Included to account for the effect of being a registered user by itself on rentals |
| `workday`| Helps identify a workday and accounts for the effect of that fact on the number of rentals for the given hour |
| Day of season | The day of the season (e.g. 0 for the first day of Spring, 1 for the second, etc...). Helps to answer [RQ.5](#rq.5) by showing if there is a significant linear relation between how long it's been a season and the number of rentals. |
| Interaction between `userType` and all other predictors | To see how registered users are affected by each other predictor compared to casual users |
